server:
  port: 8024
  address: 0.0.0.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8899/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
spring:
  application:
    name: qt-client
#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:localhost}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: ${RABBIT_MQ_USERNAME:yang}
#    password: ${RABBIT_MQ_PASSWORD:yang}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 15000
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
vpnproxy:
  enable: true
  ip: 127.0.0.1
  port: 1088

